#!/usr/bin/env bash
tmux kill-session -t "./bot/bot"
tmux kill-session -t "api"

echo "Start Launch ...."
echo "█▒▒▒▒▒▒▒▒▒ 10%"
sleep 0.5
echo ""
echo ""
echo "██▒▒▒▒▒▒▒▒ 20%"
sleep 0.5
echo ""
echo ""
echo "███▒▒▒▒▒▒▒ 30%"
sleep 0.5
echo ""
echo ""
echo "████▒▒▒▒▒▒ 40%"
sleep 0.5
echo ""
echo ""
echo "█████▒▒▒▒▒ 50%"
sleep 0.5
echo ""
echo ""
echo "██████▒▒▒▒ 60%"
sleep 0.5
echo ""
echo ""
echo "███████▒▒▒ 70%"
sleep 0.5
echo ""
echo ""
echo "████████▒▒ 80%"
sleep 0.5
echo ""
echo ""
echo "█████████▒ 90%"
sleep 0.5
echo ""
echo ""
echo "██████████ 100%"
sleep 1
tmux new-session -d -s "./bot/bot" "./CLILUNCH"
tmux detach -s "./bot/bot"
echo "Cli and Api Now Running!"
echo "... The terminal is Closed ..."
sleep 5
tmux new-session -d -s "api" "./APILUNCH"
tmux detach -s "api"